#=
End-to-end multi-worker test for AzManagers.addprocs against a real Azure
subscription. Run manually from a workstation or a small "controller" VM
inside the worker VNet to verify that:

  - templates render correctly
  - a scale set is created
  - Julia workers register with the master
  - automatic ppi (procs-per-instance) placement
    (cpu_set / numa_node / socket / pinning_backend) matches the SKU you provisioned
  - optional MPI nested launch (ppi > 1 AND mpi_ranks_per_worker > 0)
  - the scale set is torn down at the end

Each scenario is gated by a [scenarios] flag (or its SCENARIOS_<NAME> env-var
override). Set only the ones you want to run.

================================================================================
PREREQUISITES (host running this script)
================================================================================

  - Julia 1.9 or newer (package extensions ship with 1.9+)
  - This repo cloned and activated: `julia --project=. demo/multi_worker_test.jl`
  - AzSessions installed; AzManagers will be loaded from the project
  - Network access to https://management.azure.com and the worker subnet

================================================================================
AZURE RESOURCES YOU MUST HAVE
================================================================================

  1. An Azure subscription you can deploy to.
  2. A resource group in your chosen region.
  3. A VNet + subnet in that resource group. The workers will get NICs on this
     subnet, and the host running this script must be able to reach them on the
     Julia worker port (default ephemeral; see JULIA_WORKER_TIMEOUT).
  4. A Shared Image Gallery, image definition, and at least one image version
     containing:
       * Julia (matching the version flag in your `exename`)
       * AzManagers checked out and precompiled, OR `customenv=true` so the
         current project is shipped to the workers (slower bootstrap)
       * For MPI tests: an Open MPI build whose mpirun accepts
         `--cpu-set <cpu-list> --bind-to cpu-list:ordered`
       * `numactl` and `lscpu` (already present on most Ubuntu/RHEL images)
     If you don't have an image yet, the Packer file at test/image.pkr.hcl is a
     starting point.
  5. A service principal (client_id + client_secret + tenant) with Contributor
     on the resource group, OR a managed identity if you're running on Azure.

================================================================================
CONFIGURATION
================================================================================

Settings come from a TOML file (preferred) with optional env-var overrides.

Two ways to obtain a starting config:

  (a) Annotated template in this repo — fully commented, recommended:

         cp demo/multi_worker_test.toml ~/.azmanagers/multi_worker_test.toml
         chmod 600 ~/.azmanagers/multi_worker_test.toml

  (b) Minimal template generated by the script:

         julia --project=. demo/multi_worker_test.jl --init

In both cases, edit ~/.azmanagers/multi_worker_test.toml to fill in the
REPLACE-ME placeholders with values from your Azure subscription, then run:

         julia --project=. demo/multi_worker_test.jl
         julia --project=. demo/multi_worker_test.jl path/to/other.toml

TOML schema (all fields required unless marked optional):

  [azure]
  subscription_id = "..."
  resource_group  = "..."
  tenant_id       = "..."
  client_id       = "..."
  client_secret   = "..."
  vnet            = "..."
  subnet          = "..."
  gallery         = "..."
  image_name      = "..."
  location        = "southcentralus"   # optional
  sku_name        = "Standard_D4s_v5"  # optional
  ssh_user        = "cvx"              # optional
  spot            = true                # optional, Azure Spot workers

  [scenarios]
  basic        = true     # n=1, ppi=1, connectivity check
  placement    = true     # n=1, ppi=2, verify cpu_set/numa/socket
  mpi_nested   = false    # n=1, ppi=2, mpi_ranks_per_worker=2
  ppi          = 2        # procs-per-instance for placement + mpi_nested
  mpi_ranks_per_worker = 2  # optional override for mpi_nested
  mpi_flags    = ""       # optional extra mpirun flags
  expected_numa_nodes = 0 # placement: assert this many distinct NUMA nodes
                          # across workers (0 = don't check). Set per-SKU.
  expected_sockets    = 0 # placement: assert this many distinct sockets
                          # across workers (0 = don't check). Set per-SKU.
  keep         = false    # skip rmprocs/rmgroup at the end

Any TOML setting can be overridden at the command line:

  AZURE_SUBSCRIPTION_ID=...  SCENARIOS_BASIC=1  julia --project=. demo/multi_worker_test.jl

(env keys are upper-snake of section + field, joined with underscore).

================================================================================
RUN IT
================================================================================

The launcher machine (the one running this script) must be on a network with a
route to the worker subnet — Julia Distributed sets up a TCP listener on the
launcher and each worker dials back to it. In practice that means either a
small controller VM inside the same Azure VNet (recommended) or a VPN /
peering setup that drops your workstation onto that VNet. A home laptop
behind NAT cannot host the master.

  cd ~/.julia/dev/AzManagers
  cp demo/multi_worker_test.toml ~/.azmanagers/multi_worker_test.toml
  chmod 600 ~/.azmanagers/multi_worker_test.toml
  $EDITOR ~/.azmanagers/multi_worker_test.toml
  julia --project=. demo/multi_worker_test.jl

You'll see logs like:

  [ Info: writing templates for sku=Standard_HB176rs_v4
  [ Info: addprocs placement: group=mwt-place-abcd ...
  [ Info: worker 2: cpu_set=0-87 numa_node=0 socket=0 pinning_backend=numactl
  [ Info: worker 3: cpu_set=88-175 numa_node=1 socket=0 pinning_backend=numactl
  [ Info: taskset for pid 2 expected=0-87 got=pid 12345's current affinity list: 0-87
  [ Info: teardown complete for scale set mwt-place-abcd

================================================================================
HOW TO CLEAN UP IF SOMETHING WEDGES
================================================================================

  az vmss list -g $RESOURCE_GROUP --query "[?starts_with(name,'mwt')].name" -o tsv \
      | xargs -I {} az vmss delete -g $RESOURCE_GROUP -n {}

=#

using Distributed, AzManagers, AzSessions, Random, Test, HTTP, JSON, TOML

const TEMPLATE_NAME       = "mwt" * randstring('a':'z', 4)
const DEFAULT_CONFIG_PATH = joinpath(homedir(), ".azmanagers", "multi_worker_test.toml")

const TEMPLATE_TOML = """
[azure]
subscription_id = "REPLACE-ME"
resource_group  = "REPLACE-ME"
tenant_id       = "REPLACE-ME"
client_id       = "REPLACE-ME"
client_secret   = "REPLACE-ME"
vnet            = "REPLACE-ME"
subnet          = "REPLACE-ME"
gallery         = "REPLACE-ME"
image_name      = "REPLACE-ME"
location        = "southcentralus"
sku_name        = "Standard_D4s_v5"
ssh_user        = "cvx"
spot            = true

[scenarios]
basic                 = true
placement             = false
mpi_nested            = false
ppi                   = 2
mpi_ranks_per_worker  = 2
mpi_flags             = ""
expected_numa_nodes   = 0
expected_sockets      = 0
keep                  = false
"""

function init_config(path)
    if isfile(path)
        @info "config already exists at $path; not overwriting"
        return
    end
    mkpath(dirname(path))
    write(path, TEMPLATE_TOML)
    try
        chmod(path, 0o600)
    catch
    end
    @info "wrote template config to $path; edit it and rerun"
end

function load_config(path)
    isfile(path) ||
        error("config file $path does not exist; run with --init to create a template")
    TOML.parsefile(path)
end

function get_field(cfg, section, field; default = nothing, required = true)
    env_key = uppercase(string(section, "_", field))
    if haskey(ENV, env_key)
        return ENV[env_key]
    end
    section_table = get(cfg, string(section), Dict())
    if haskey(section_table, string(field))
        return section_table[string(field)]
    end
    default !== nothing && return default
    required && error("missing config field [$section].$field (or env var $env_key)")
    nothing
end

function get_bool(cfg, section, field; default = false)
    value = get_field(cfg, section, field; default = default, required = false)
    value isa Bool && return value
    value isa AbstractString && return lowercase(value) in ("1", "true", "yes")
    Bool(value)
end

function get_int(cfg, section, field; default)
    value = get_field(cfg, section, field; default = default, required = false)
    value isa Integer && return Int(value)
    parse(Int, string(value))
end

function build_test_templates(cfg)
    subscriptionid = get_field(cfg, :azure, :subscription_id)
    resourcegroup  = get_field(cfg, :azure, :resource_group)
    tenant_id      = get_field(cfg, :azure, :tenant_id)
    client_id      = get_field(cfg, :azure, :client_id)
    client_secret  = get_field(cfg, :azure, :client_secret)
    vnet           = get_field(cfg, :azure, :vnet)
    subnet         = get_field(cfg, :azure, :subnet)
    gallery        = get_field(cfg, :azure, :gallery)
    imagename      = get_field(cfg, :azure, :image_name)
    location       = get_field(cfg, :azure, :location; default = "southcentralus", required = false)
    sku            = get_field(cfg, :azure, :sku_name; default = "Standard_D4s_v5", required = false)
    ssh_user       = get_field(cfg, :azure, :ssh_user; default = "cvx", required = false)

    @info "writing templates for sku=$sku location=$location"

    sstemplate = AzManagers.build_sstemplate(
        TEMPLATE_NAME;
        subscriptionid     = subscriptionid,
        admin_username     = ssh_user,
        location           = location,
        resourcegroup      = resourcegroup,
        resourcegroup_vnet = resourcegroup,
        vnet               = vnet,
        subnet             = subnet,
        imagegallery       = gallery,
        imagename          = imagename,
        skuname            = sku)

    nictemplate = AzManagers.build_nictemplate(
        TEMPLATE_NAME;
        accelerated        = false,
        subscriptionid     = subscriptionid,
        location           = location,
        resourcegroup_vnet = resourcegroup,
        vnet               = vnet,
        subnet             = subnet)

    AzManagers.save_template_scaleset(TEMPLATE_NAME, sstemplate)
    AzManagers.save_template_nic(TEMPLATE_NAME, nictemplate)

    AzSessions.write_manifest(;
        client_id     = client_id,
        client_secret = client_secret,
        tenant        = tenant_id)
    AzManagers.write_manifest(;
        resourcegroup  = resourcegroup,
        subscriptionid = subscriptionid,
        ssh_user       = ssh_user)

    AzSession(; protocal = AzClientCredentials)
end

function dump_worker_placements()
    placements = worker_placements()
    for pid in sort(collect(keys(placements)))
        info = placements[pid]
        cpu_set  = get(info, "cpu_set", "?")
        numa     = get(info, "numa_node", "?")
        socket   = get(info, "socket", "?")
        backend  = get(info, "pinning_backend", "?")
        threads  = get(info, "julia_threads", "?")
        @info "worker $pid: cpu_set=$cpu_set numa_node=$numa socket=$socket julia_threads=$threads backend=$backend"
    end
    placements
end

function assert_taskset_matches(placements)
    for pid in workers()
        info = get(placements, pid, Dict())
        expected = get(info, "cpu_set", "")
        affinity = remotecall_fetch(pid) do
            try
                strip(read(`taskset -pc $(getpid())`, String))
            catch e
                "taskset failed: $e"
            end
        end
        @info "taskset for pid $pid expected=$expected got=$affinity"
    end
end

function teardown(cfg, group)
    if get_bool(cfg, :scenarios, :keep)
        @warn "scenarios.keep=true; leaving workers + scale set '$group' running"
        return
    end
    isempty(workers()) || rmprocs(workers())
    try
        AzManagers.rmgroup(group)
    catch e
        @warn "rmgroup($group) failed; check scale set manually" exception=e
    end
    @info "teardown complete for scale set $group"
end

function run_basic_scenario(cfg, session)
    group = "mwt-basic-" * randstring('a':'z', 4)
    spot  = get_bool(cfg, :azure, :spot; default = true)
    @info "addprocs basic: group=$group n=1 ppi=1 spot=$spot"
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor = true,
        ppi     = 1,
        spot    = spot,
        group,
        session)
    try
        @assert nworkers() == 1
        hostname = remotecall_fetch(gethostname, first(workers()))
        @info "basic worker hostname=$hostname"
    finally
        teardown(cfg, group)
    end
end

function run_placement_scenario(cfg, session)
    group = "mwt-place-" * randstring('a':'z', 4)
    ppi   = get_int(cfg, :scenarios, :ppi; default = 2)
    spot  = get_bool(cfg, :azure, :spot; default = true)
    @info "addprocs placement: group=$group n=1 ppi=$ppi spot=$spot"
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor = true,
        ppi     = ppi,
        spot    = spot,
        group,
        session)
    try
        @assert nworkers() == ppi
        placements = dump_worker_placements()
        cpu_sets = [get(p, "cpu_set", "") for p in values(placements)]
        @assert all(!isempty, cpu_sets) "some workers reported empty cpu_set"
        @assert length(unique(cpu_sets)) == ppi "cpu_sets are not disjoint: $cpu_sets"
        assert_taskset_matches(placements)
        assert_topology_matches(cfg, placements)
    finally
        teardown(cfg, group)
    end
end

# Optional per-SKU topology assertion. The matrix shard sets
# SCENARIOS_EXPECTED_NUMA_NODES / SCENARIOS_EXPECTED_SOCKETS (or the equivalent
# [scenarios] expected_numa_nodes / expected_sockets keys); each is the count
# of distinct values the planner is expected to assign across ppi workers.
# Missing/zero means "don't check".
function assert_topology_matches(cfg, placements)
    expected_numa = get_int(cfg, :scenarios, :expected_numa_nodes; default = 0)
    expected_sock = get_int(cfg, :scenarios, :expected_sockets;    default = 0)

    if expected_numa > 0
        observed = unique(get(p, "numa_node", nothing) for p in values(placements))
        @info "topology: expected_numa_nodes=$expected_numa observed=$(sort(collect(observed)))"
        @assert length(observed) == expected_numa "numa_node distribution mismatch: \
            expected $expected_numa distinct nodes, observed $(length(observed)): $observed"
    end

    if expected_sock > 0
        observed = unique(get(p, "socket", nothing) for p in values(placements))
        @info "topology: expected_sockets=$expected_sock observed=$(sort(collect(observed)))"
        @assert length(observed) == expected_sock "socket distribution mismatch: \
            expected $expected_sock distinct sockets, observed $(length(observed)): $observed"
    end
end

function run_mpi_nested_scenario(cfg, session)
    group                = "mwt-mpi-" * randstring('a':'z', 4)
    ppi                  = get_int(cfg, :scenarios, :ppi; default = 2)
    mpi_ranks_per_worker = get_int(cfg, :scenarios, :mpi_ranks_per_worker; default = 2)
    spot                 = get_bool(cfg, :azure, :spot; default = true)
    # mpi_flags defaults to "" so the auto-emitted `--bind-to cpu-list:ordered`
    # is not overridden. Set scenarios.mpi_flags in the TOML if your image
    # needs extra mpirun flags.
    mpi_flags = string(get_field(cfg, :scenarios, :mpi_flags; default = "", required = false))
    @info "addprocs MPI nested: group=$group ppi=$ppi mpi_ranks_per_worker=$mpi_ranks_per_worker spot=$spot"
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor              = true,
        ppi                  = ppi,
        mpi_ranks_per_worker = mpi_ranks_per_worker,
        mpi_flags            = mpi_flags,
        spot                 = spot,
        group,
        session)
    try
        @assert nworkers() == ppi "expected $ppi julia workers, got $(nworkers())"
        for pid in workers()
            rank_count = remotecall_fetch(pid) do
                try
                    Base.invokelatest(eval, :(using MPI; MPI.Comm_size(MPI.COMM_WORLD)))
                catch e
                    "MPI introspection failed: $e"
                end
            end
            @info "worker $pid MPI.Comm_size=$rank_count"
        end
        dump_worker_placements()
    finally
        teardown(cfg, group)
    end
end

function main()
    if !isempty(ARGS) && ARGS[1] == "--init"
        path = length(ARGS) >= 2 ? ARGS[2] : DEFAULT_CONFIG_PATH
        init_config(path)
        return
    end

    config_path = isempty(ARGS) ? DEFAULT_CONFIG_PATH : ARGS[1]
    cfg = load_config(config_path)
    @info "loaded config from $config_path"

    session = build_test_templates(cfg)

    any_run = false
    if get_bool(cfg, :scenarios, :basic);      any_run = true; run_basic_scenario(cfg, session); end
    if get_bool(cfg, :scenarios, :placement);  any_run = true; run_placement_scenario(cfg, session); end
    if get_bool(cfg, :scenarios, :mpi_nested); any_run = true; run_mpi_nested_scenario(cfg, session); end
    any_run || @warn "no scenario enabled in $config_path; flip [scenarios] entries to true"
end

main()
