#=
End-to-end multi-worker test for AzManagers.addprocs against a real Azure
subscription. Run manually from a workstation or a small "controller" VM
inside the worker VNet to verify that:

  - templates render correctly
  - a scale set is created
  - Julia workers register with the master
  - automatic ppi (procs-per-instance) placement
    (cpu_set / numa_node / socket / pinning_backend) matches the SKU you provisioned
  - optional MPI nested launch (ppi > 1 AND mpi_ranks_per_worker > 0)
  - the scale set is torn down at the end

Each scenario is gated by a [scenarios] flag (or its SCENARIOS_<NAME> env-var
override). Set only the ones you want to run.

================================================================================
PREREQUISITES (host running this script)
================================================================================

  - Julia 1.9 or newer (package extensions ship with 1.9+)
  - This repo cloned and activated: `julia --project=. demo/multi_worker_test.jl`
  - AzSessions installed; AzManagers will be loaded from the project
  - Network access to https://management.azure.com and the worker subnet

================================================================================
AZURE RESOURCES YOU MUST HAVE
================================================================================

  1. An Azure subscription you can deploy to.
  2. A resource group in your chosen region.
  3. A VNet + subnet in that resource group. The workers will get NICs on this
     subnet, and the host running this script must be able to reach them on the
     Julia worker port (default ephemeral; see JULIA_WORKER_TIMEOUT).
  4. A Shared Image Gallery, image definition, and at least one image version
     containing:
       * Julia (matching the version flag in your `exename`)
       * AzManagers checked out and precompiled, OR `customenv=true` so the
         current project is shipped to the workers (slower bootstrap)
       * For MPI tests: an Open MPI build whose mpirun accepts
         `--cpu-set <cpu-list> --bind-to cpu-list:ordered`
       * `numactl` and `lscpu` (already present on most Ubuntu/RHEL images)
     If you don't have an image yet, the Packer file at test/image.pkr.hcl is a
     starting point.
  5. A service principal (client_id + client_secret + tenant) with Contributor
     on the resource group, OR a managed identity if you're running on Azure.

================================================================================
CONFIGURATION
================================================================================

Settings come from a TOML file (preferred) with optional env-var overrides.

Two ways to obtain a starting config:

  (a) Annotated template in this repo — fully commented, recommended:

         cp demo/multi_worker_test.toml ~/.azmanagers/multi_worker_test.toml
         chmod 600 ~/.azmanagers/multi_worker_test.toml

  (b) Minimal template generated by the script:

         julia --project=. demo/multi_worker_test.jl --init

In both cases, edit ~/.azmanagers/multi_worker_test.toml to fill in the
REPLACE-ME placeholders with values from your Azure subscription, then run:

         julia --project=. demo/multi_worker_test.jl
         julia --project=. demo/multi_worker_test.jl path/to/other.toml

TOML schema (all fields required unless marked optional):

  [azure]
  subscription_id = "..."
  resource_group  = "..."
  tenant_id       = "..."
  client_id       = "..."
  client_secret   = "..."
  vnet            = "..."
  subnet          = "..."
  gallery         = "..."
  image_name      = "..."
  location        = "southcentralus"   # optional
  sku_name        = "Standard_D4s_v5"  # optional
  ssh_user        = "cvx"              # optional
  spot            = true                # optional, Azure Spot workers

  [scenarios]
  basic        = true     # n=1, ppi=1, connectivity check
  placement    = true     # n=1, ppi=2, verify cpu_set/numa/socket
  mpi_nested   = false    # n=1, ppi=2, mpi_ranks_per_worker=2
  ppi          = 2        # procs-per-instance for placement + mpi_nested
  mpi_ranks_per_worker = 2  # optional override for mpi_nested
  mpi_flags    = ""       # optional extra mpirun flags
  expected_numa_nodes = 0 # placement: assert this many distinct NUMA nodes
                          # across workers (0 = don't check). Set per-SKU.
  expected_sockets    = 0 # placement: assert this many distinct sockets
                          # across workers (0 = don't check). Set per-SKU.
  keep         = false    # skip rmprocs/rmgroup at the end

Any TOML setting can be overridden at the command line:

  AZURE_SUBSCRIPTION_ID=...  SCENARIOS_BASIC=1  julia --project=. demo/multi_worker_test.jl

(env keys are upper-snake of section + field, joined with underscore).

================================================================================
RUN IT
================================================================================

The launcher machine (the one running this script) must be on a network with a
route to the worker subnet — Julia Distributed sets up a TCP listener on the
launcher and each worker dials back to it. In practice that means either a
small controller VM inside the same Azure VNet (recommended) or a VPN /
peering setup that drops your workstation onto that VNet. A home laptop
behind NAT cannot host the master.

  cd ~/.julia/dev/AzManagers
  cp demo/multi_worker_test.toml ~/.azmanagers/multi_worker_test.toml
  chmod 600 ~/.azmanagers/multi_worker_test.toml
  $EDITOR ~/.azmanagers/multi_worker_test.toml
  julia --project=. demo/multi_worker_test.jl

You'll see logs like:

  [ Info: writing templates for sku=Standard_HB176rs_v4
  [ Info: addprocs placement: group=mwt-place-abcd ...
  [ Info: worker 2: cpu_set=0-87 numa_node=0 socket=0 pinning_backend=numactl
  [ Info: worker 3: cpu_set=88-175 numa_node=1 socket=0 pinning_backend=numactl
  [ Info: taskset for pid 2 expected=0-87 got=pid 12345's current affinity list: 0-87
  [ Info: teardown complete for scale set mwt-place-abcd

================================================================================
HOW TO CLEAN UP IF SOMETHING WEDGES
================================================================================

  az vmss list -g $RESOURCE_GROUP --query "[?starts_with(name,'mwt')].name" -o tsv \
      | xargs -I {} az vmss delete -g $RESOURCE_GROUP -n {}

=#

using Distributed, AzManagers, AzSessions, Random, Test, HTTP, JSON, TOML

const TEMPLATE_NAME       = "mwt" * randstring('a':'z', 4)
const DEFAULT_CONFIG_PATH = joinpath(homedir(), ".azmanagers", "multi_worker_test.toml")

const TEMPLATE_TOML = """
[azure]
subscription_id = "REPLACE-ME"
resource_group  = "REPLACE-ME"
tenant_id       = "REPLACE-ME"
client_id       = "REPLACE-ME"
client_secret   = "REPLACE-ME"
vnet            = "REPLACE-ME"
subnet          = "REPLACE-ME"
gallery         = "REPLACE-ME"
image_name      = "REPLACE-ME"
location        = "southcentralus"
sku_name        = "Standard_D4s_v5"
ssh_user        = "cvx"
spot            = true

[scenarios]
basic                 = true
placement             = false
mpi_nested            = false
ppi                   = 2
mpi_ranks_per_worker  = 2
mpi_flags             = ""
expected_numa_nodes   = 0
expected_sockets      = 0
keep                  = false
"""

function init_config(path)
    if isfile(path)
        @info "config already exists at $path; not overwriting"
        return
    end
    mkpath(dirname(path))
    write(path, TEMPLATE_TOML)
    try
        chmod(path, 0o600)
    catch
    end
    @info "wrote template config to $path; edit it and rerun"
end

function load_config(path)
    isfile(path) ||
        error("config file $path does not exist; run with --init to create a template")
    TOML.parsefile(path)
end

function get_field(cfg, section, field; default = nothing, required = true)
    env_key = uppercase(string(section, "_", field))
    if haskey(ENV, env_key)
        return ENV[env_key]
    end
    section_table = get(cfg, string(section), Dict())
    if haskey(section_table, string(field))
        return section_table[string(field)]
    end
    default !== nothing && return default
    required && error("missing config field [$section].$field (or env var $env_key)")
    nothing
end

function get_bool(cfg, section, field; default = false)
    value = get_field(cfg, section, field; default = default, required = false)
    value isa Bool && return value
    value isa AbstractString && return lowercase(value) in ("1", "true", "yes")
    Bool(value)
end

function get_int(cfg, section, field; default)
    value = get_field(cfg, section, field; default = default, required = false)
    value isa Integer && return Int(value)
    parse(Int, string(value))
end

function build_test_templates(cfg)
    subscriptionid = get_field(cfg, :azure, :subscription_id)
    resourcegroup  = get_field(cfg, :azure, :resource_group)
    tenant_id      = get_field(cfg, :azure, :tenant_id)
    client_id      = get_field(cfg, :azure, :client_id)
    client_secret  = get_field(cfg, :azure, :client_secret)
    vnet           = get_field(cfg, :azure, :vnet)
    subnet         = get_field(cfg, :azure, :subnet)
    gallery        = get_field(cfg, :azure, :gallery)
    imagename      = get_field(cfg, :azure, :image_name)
    location       = get_field(cfg, :azure, :location; default = "southcentralus", required = false)
    sku            = get_field(cfg, :azure, :sku_name; default = "Standard_D4s_v5", required = false)
    ssh_user       = get_field(cfg, :azure, :ssh_user; default = "cvx", required = false)

    @info "writing templates for sku=$sku location=$location"

    sstemplate = AzManagers.build_sstemplate(
        TEMPLATE_NAME;
        subscriptionid     = subscriptionid,
        admin_username     = ssh_user,
        location           = location,
        resourcegroup      = resourcegroup,
        resourcegroup_vnet = resourcegroup,
        vnet               = vnet,
        subnet             = subnet,
        imagegallery       = gallery,
        imagename          = imagename,
        skuname            = sku)

    nictemplate = AzManagers.build_nictemplate(
        TEMPLATE_NAME;
        accelerated        = false,
        subscriptionid     = subscriptionid,
        location           = location,
        resourcegroup_vnet = resourcegroup,
        vnet               = vnet,
        subnet             = subnet)

    AzManagers.save_template_scaleset(TEMPLATE_NAME, sstemplate)
    AzManagers.save_template_nic(TEMPLATE_NAME, nictemplate)

    AzSessions.write_manifest(;
        client_id     = client_id,
        client_secret = client_secret,
        tenant        = tenant_id)
    AzManagers.write_manifest(;
        resourcegroup  = resourcegroup,
        subscriptionid = subscriptionid,
        ssh_user       = ssh_user)

    AzSession(; protocal = AzClientCredentials)
end

function log_section(title)
    bar = "=" ^ 70
    @info bar
    @info title
    @info bar
end

"""
Probe one worker for the SKU's machine topology and log it. Gives a
clear reference point for what placement is being computed against,
before any per-worker placement is dumped.
"""
function dump_machine_topology()
    log_section("Machine topology (as seen by worker $(first(workers())))")
    topo = remotecall_fetch(first(workers())) do
        try
            t = AzManagers.detect_machine_topology()
            (
                ok = true,
                physical_cores = t.physical_cores,
                logical_cpus   = length(t.logical_cpus),
                hyperthreading = t.hyperthreading,
                sockets        = length(t.sockets),
                numa_nodes     = length(t.numa_nodes),
                socket_cpus    = [(s.id, length(s.cpu_set)) for s in t.sockets],
                numa_cpus      = [(n.id, n.socket_id, length(n.cpu_set)) for n in t.numa_nodes],
            )
        catch e
            (ok = false, error = sprint(showerror, e))
        end
    end
    if !topo.ok
        @warn "detect_machine_topology failed on worker" error=topo.error
        return
    end
    @info("topology",
          physical_cores = topo.physical_cores,
          logical_cpus   = topo.logical_cpus,
          hyperthreading = topo.hyperthreading,
          sockets        = topo.sockets,
          numa_nodes     = topo.numa_nodes)
    for (sid, ncpu) in topo.socket_cpus
        @info "  socket $sid: $ncpu logical CPUs"
    end
    for (nid, sid, ncpu) in topo.numa_cpus
        @info "  numa $nid (socket $sid): $ncpu logical CPUs"
    end
end

function dump_worker_placements()
    log_section("Per-worker placement (planner output, recorded at handshake)")
    placements = worker_placements()
    for pid in sort(collect(keys(placements)))
        info = placements[pid]
        hostname = try
            remotecall_fetch(gethostname, pid)
        catch
            "<unreachable>"
        end
        # `@info(msg, k=v...)` produces a multi-line log entry with each
        # key on its own line - much easier to scan in CI than the single
        # "k=v k=v k=v" form.
        @info("worker pid=$pid",
              hostname        = hostname,
              localid         = get(info, "localid", "?"),
              cpu_set         = get(info, "cpu_set", "?"),
              numa_node       = get(info, "numa_node", "?"),
              socket          = get(info, "socket", "?"),
              julia_threads   = get(info, "julia_threads", "?"),
              pinning_backend = get(info, "pinning_backend", "?"),
              physical_cores  = get(info, "physical_cores", "?"),
              omp_threads     = get(info, "omp_threads", "?"))
    end
    placements
end

function check_taskset_matches(placements)
    log_section("taskset affinity check (kernel-observed vs planner expected)")
    for pid in workers()
        info = get(placements, pid, Dict())
        expected = get(info, "cpu_set", "")
        affinity = remotecall_fetch(pid) do
            try
                strip(read(`taskset -pc $(getpid())`, String))
            catch e
                "taskset failed: $e"
            end
        end
        # The `affinity` line from taskset is "pid <N>'s current affinity list: <range>"
        # - assert the expected range is in there. Empty `expected` is the
        # ppi=1 path where no cpu_set was planned; skip in that case.
        if isempty(expected)
            @info "pid $pid: no cpu_set planned (ppi=1 path); skipping affinity check" taskset=affinity
        else
            match = occursin(expected, affinity)
            if match
                @info "pid $pid: PASS" expected=expected taskset=affinity
            else
                @warn "pid $pid: FAIL - expected '$expected' not present in affinity" expected=expected taskset=affinity
            end
            @test match
        end
    end
end

"""
Print a per-worker side-by-side comparison of what each worker is bound
to (cpu_set, NUMA, socket) so you can eyeball whether the distribution
makes sense for the SKU and ppi.
"""
function dump_distribution_summary(placements)
    log_section("Placement distribution summary")
    cpu_sets  = unique(get(p, "cpu_set",   "")       for p in values(placements))
    numas     = unique(get(p, "numa_node", nothing)  for p in values(placements))
    sockets   = unique(get(p, "socket",    nothing)  for p in values(placements))
    @info("distinct counts across workers",
          workers        = length(placements),
          unique_cpu_sets = length(cpu_sets),
          unique_numa    = length(numas),
          unique_sockets = length(sockets),
          numa_values    = sort(collect(numas);    by = x -> something(x, -1)),
          socket_values  = sort(collect(sockets);  by = x -> something(x, -1)),
          cpu_sets       = sort(collect(cpu_sets)))
end

function teardown(cfg, group, session)
    if get_bool(cfg, :scenarios, :keep)
        @warn "scenarios.keep=true; leaving workers + scale set '$group' running"
        return
    end
    isempty(workers()) || rmprocs(workers())
    try
        # `rmgroup` defaults to `session=AzSession(;lazy=true)` which on
        # first token() falls through to device-code flow - hangs the
        # CI shard for 15 minutes then errors expired_token. Pass the
        # service-principal session explicitly.
        AzManagers.rmgroup(group; session=session)
    catch e
        @warn "rmgroup($group) failed; check scale set manually" exception=e
    end
    @info "teardown complete for scale set $group"
end

function run_basic_scenario(cfg, session)
    group = "mwt-basic-" * randstring('a':'z', 4)
    spot  = get_bool(cfg, :azure, :spot; default = true)
    log_section("Basic scenario: ppi=1, n=1, spot=$spot, group=$group")
    @info "calling addprocs..."
    t_start = time()
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor = true,
        ppi     = 1,
        spot    = spot,
        group,
        session)
    @info "addprocs returned" elapsed_s=round(time() - t_start; digits=1) nworkers=nworkers()
    try
        @testset "basic scenario" begin
            @test nworkers() == 1
            pid = first(workers())
            hostname = remotecall_fetch(gethostname, pid)
            @info "worker pid=$pid hostname=$hostname"
        end
    finally
        teardown(cfg, group, session)
    end
end

function run_placement_scenario(cfg, session)
    group = "mwt-place-" * randstring('a':'z', 4)
    ppi   = get_int(cfg, :scenarios, :ppi; default = 2)
    spot  = get_bool(cfg, :azure, :spot; default = true)
    expected_numa = get_int(cfg, :scenarios, :expected_numa_nodes; default = 0)
    expected_sock = get_int(cfg, :scenarios, :expected_sockets;    default = 0)
    sku   = get_field(cfg, :azure, :sku_name; default = "?")

    log_section("Placement scenario: SKU=$sku ppi=$ppi n=1 spot=$spot")
    @info("expected (from matrix shard)",
          ppi               = ppi,
          distinct_numa     = expected_numa,
          distinct_sockets  = expected_sock,
          interpretation    = "each of $ppi workers should land on its own slice; counts above are how many UNIQUE values across workers")
    @info "calling addprocs..." group=group
    t_start = time()
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor = true,
        ppi     = ppi,
        spot    = spot,
        group,
        session)
    @info "addprocs returned" elapsed_s=round(time() - t_start; digits=1) nworkers=nworkers()
    try
        @testset "placement scenario (ppi=$ppi)" begin
            @test nworkers() == ppi
            dump_machine_topology()
            placements = dump_worker_placements()
            dump_distribution_summary(placements)
            cpu_sets = [get(p, "cpu_set", "") for p in values(placements)]
            @test all(!isempty, cpu_sets)
            @test length(unique(cpu_sets)) == ppi
            check_taskset_matches(placements)
            check_topology_matches(cfg, placements)
        end
    finally
        teardown(cfg, group, session)
    end
end

# Optional per-SKU topology assertion. The matrix shard sets
# SCENARIOS_EXPECTED_NUMA_NODES / SCENARIOS_EXPECTED_SOCKETS (or the equivalent
# [scenarios] expected_numa_nodes / expected_sockets keys); each is the count
# of distinct values the planner is expected to assign across ppi workers.
# Missing/zero means "don't check".
function check_topology_matches(cfg, placements)
    log_section("Topology distribution check (matrix-defined expectations)")
    expected_numa = get_int(cfg, :scenarios, :expected_numa_nodes; default = 0)
    expected_sock = get_int(cfg, :scenarios, :expected_sockets;    default = 0)

    if expected_numa > 0
        observed = sort(collect(unique(get(p, "numa_node", nothing) for p in values(placements)));
                        by = x -> something(x, -1))
        observed_distinct = length(observed)
        if observed_distinct == expected_numa
            @info "numa_node distribution: PASS" expected_distinct=expected_numa observed_distinct=observed_distinct observed_values=observed
        else
            @warn "numa_node distribution: FAIL" expected_distinct=expected_numa observed_distinct=observed_distinct observed_values=observed
        end
        @test observed_distinct == expected_numa
    else
        @info "numa_node distribution: skipped (expected_numa_nodes=0)"
    end

    if expected_sock > 0
        observed = sort(collect(unique(get(p, "socket", nothing) for p in values(placements)));
                        by = x -> something(x, -1))
        observed_distinct = length(observed)
        if observed_distinct == expected_sock
            @info "socket distribution: PASS" expected_distinct=expected_sock observed_distinct=observed_distinct observed_values=observed
        else
            @warn "socket distribution: FAIL" expected_distinct=expected_sock observed_distinct=observed_distinct observed_values=observed
        end
        @test observed_distinct == expected_sock
    else
        @info "socket distribution: skipped (expected_sockets=0)"
    end
end

function run_mpi_nested_scenario(cfg, session)
    group                = "mwt-mpi-" * randstring('a':'z', 4)
    ppi                  = get_int(cfg, :scenarios, :ppi; default = 2)
    mpi_ranks_per_worker = get_int(cfg, :scenarios, :mpi_ranks_per_worker; default = 2)
    spot                 = get_bool(cfg, :azure, :spot; default = true)
    sku                  = get_field(cfg, :azure, :sku_name; default = "?")
    # mpi_flags defaults to "" so the auto-emitted `--bind-to cpu-list:ordered`
    # is not overridden. Set scenarios.mpi_flags in the TOML if your image
    # needs extra mpirun flags.
    mpi_flags = string(get_field(cfg, :scenarios, :mpi_flags; default = "", required = false))

    log_section("MPI-nested scenario: SKU=$sku ppi=$ppi ranks/worker=$mpi_ranks_per_worker spot=$spot")
    @info("expected",
          julia_workers       = ppi,
          mpi_ranks_per_worker = mpi_ranks_per_worker,
          total_mpi_ranks      = ppi * mpi_ranks_per_worker,
          mpi_flags            = mpi_flags)
    @info "calling addprocs..." group=group
    t_start = time()
    addprocs(AzManager(), TEMPLATE_NAME, 1;
        waitfor              = true,
        ppi                  = ppi,
        mpi_ranks_per_worker = mpi_ranks_per_worker,
        mpi_flags            = mpi_flags,
        spot                 = spot,
        group,
        session)
    @info "addprocs returned" elapsed_s=round(time() - t_start; digits=1) nworkers=nworkers()
    try
        @testset "MPI nested scenario (ppi=$ppi, ranks/worker=$mpi_ranks_per_worker)" begin
            @test nworkers() == ppi
            log_section("MPI rank introspection (one MPI.Comm_size call per worker)")
            for pid in workers()
                hostname = try; remotecall_fetch(gethostname, pid); catch; "<unreachable>"; end
                rank_count = remotecall_fetch(pid) do
                    try
                        Base.invokelatest(eval, :(using MPI; MPI.Comm_size(MPI.COMM_WORLD)))
                    catch e
                        "MPI introspection failed: $e"
                    end
                end
                if rank_count == mpi_ranks_per_worker
                    @info "pid $pid: PASS" hostname=hostname expected=mpi_ranks_per_worker got=rank_count
                else
                    @warn "pid $pid: FAIL" hostname=hostname expected=mpi_ranks_per_worker got=rank_count
                end
                @test rank_count == mpi_ranks_per_worker
            end
            dump_machine_topology()
            placements = dump_worker_placements()
            dump_distribution_summary(placements)
        end
    finally
        teardown(cfg, group, session)
    end
end

function main()
    if !isempty(ARGS) && ARGS[1] == "--init"
        path = length(ARGS) >= 2 ? ARGS[2] : DEFAULT_CONFIG_PATH
        init_config(path)
        return
    end

    config_path = isempty(ARGS) ? DEFAULT_CONFIG_PATH : ARGS[1]
    cfg = load_config(config_path)
    @info "loaded config from $config_path"

    session = build_test_templates(cfg)

    any_run = false
    if get_bool(cfg, :scenarios, :basic);      any_run = true; run_basic_scenario(cfg, session); end
    if get_bool(cfg, :scenarios, :placement);  any_run = true; run_placement_scenario(cfg, session); end
    if get_bool(cfg, :scenarios, :mpi_nested); any_run = true; run_mpi_nested_scenario(cfg, session); end
    any_run || @warn "no scenario enabled in $config_path; flip [scenarios] entries to true"
end

main()
