name: Unit Tests

on:
  pull_request:
  push:
    branches: [master]

jobs:
  unit:
    name: Julia ${{ matrix.version }} unit tests
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        version:
          - '1'
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.version }}
      - run: julia --project=. -e 'using Pkg; Pkg.instantiate()'
      - run: julia --project=. test/unit.jl

